### ISSUE TITLE
Can't load because windows keeps on saying its a trojan

### ISSUE THREAD

**Issue by quri1q** [ValidHunters/Marseyloader#11]
Can't load because windows keeps on saying its a trojan, its as simple as that

**Comment by robustgreytider** [comment]
install linux

**Comment by Subversionary** [comment]
1. Provide more info - Windows ver, AV used and the file its mad about
2. I have approximately zero clue what is avast/avg in particular is mad about, as it seems like a general issue with the Space Station 14 launcher.
3. Virustotal for Marsey.dll, containing most of the code contributed and everything concerning patching.
https://www.virustotal.com/gui/file/b700ef9528b1d712d8a49aae1bf8024e212f4edef77b3c1fb280fd0c473d74f2/detection

**Comment by Subversionary** [comment]
Preemptively applying avast flari until proven otherwise

**Comment by Subversionary** [comment]
OP has been assassinated by Kaspersky SVR RF operatives
