### ISSUE TITLE
Троянчики ребятки

### ISSUE THREAD

**Issue by DoezonCanoe** [ValidHunters/Marseyloader#3]
https://cdn.discordapp.com/attachments/1161623190502645793/1173696938537926726/image.png?ex=6564e574&is=65527074&hm=955bc7614c3ab2102980fdd83d83daa94679f1601a82d3afbb96e7eb871bc583& https://github.com/ValidHunters/Marseyloader/releases/tag/ver-905386d4b615312aa9c313aabf10d0b7a27f1fb4

**Comment by Subversionary** [comment]
>ВТ на проект с полным исходным кодом
>Даже не показывает что просканировал

![IMG_2517](https://github.com/ValidHunters/Marseyloader/assets/109166122/d9f79f72-5398-487e-8bb5-ba5f4de66b78)

**Comment by Sakurey** [comment]
Круто у меня украли все деньги у меня пк долбится 100 из за майнеров у там какойто юзер администратор OlegFromBBT

**Comment by Subversionary** [comment]
> Круто у меня украли все деньги у меня пк долбится 100 из за майнеров у там какойто юзер администратор OlegFromBBT

патч иссуе

**Comment by Sakurey** [comment]
Басед
