### ISSUE TITLE
Not working on mac

### ISSUE THREAD

**Issue by Theresha15zshak** [ValidHunters/Marseyloader#47]
Not working on mac. When i'm trying to open, it it just closes.

**Comment by misandrie** [comment]
Stacktrace?

**Comment by Theresha15zshak** [comment]
So i find out how to fix this. Open marsey launcher, go to Contents/Macos, create folder Marsey and in it folder ResourcePacks.

**Comment by misandrie** [comment]
The script isnt creating the folder, weird. Thank you for the headsup
