### ISSUE TITLE
I cant connect to servers.

### ISSUE THREAD

**Issue by Afavertov** [ValidHunters/Marseyloader#6]
![изображение](https://github.com/ValidHunters/Marseyloader/assets/89081329/105379ce-2333-4ef6-85fa-5c7d0dba62bf)

**Comment by Subversionary** [comment]
What version of the loader are you using? Whats the output of client.stderr.log?

**Comment by Subversionary** [comment]
Considering the timing of the issue it appears you've attempted to join a server running .NET 8. Install .NET 8 runtime and update to v2.6.1

https://github.com/ValidHunters/Marseyloader/releases/tag/ver-12687f69fe3979205e4634247b0cd4f5b6ee23e8

**Comment by Afavertov** [comment]
It worked.
